### ISSUE TITLE
Investigate/remove duplicate URIs in overlapping sets

### ISSUE THREAD

**Issue by jeremykubica** [dirac-institute/kbmod#494]
Determine why region search is currently finding duplicate URIs and make sure they are filtered.

**Comment by wilsonbb** [comment]
In the recent E2E demo where we saw this error, this turned out to be due to a bug where I was accidentally querying across multiple collections in the butler repo. The original overlapping sets code in the [Region Searching Workbook.ipynb](https://github.com/dirac-institute/kbmod/blob/f39e379f45cf1c01ca4e7f341ab86ea68d1f44f9/notebooks/region_search/Region%20Searching%20Workbook.ipynb) did not have this error.

Will be adding a specific test for this in the region search library (see https://github.com/dirac-institute/kbmod/issues/496)
