### ISSUE TITLE
Need feedback/progress updates to user during reproject, etc.

### ISSUE THREAD

**Issue by ColinOrionChandler** [dirac-institute/kbmod#641]
Ideally, an indicator of the time remaining too, but at the very least letting the user see what is happening during the course of multi-hour operations like constructing work units.

**Comment by maxwest-uw** [comment]
1. I think this refers to the creation of a `WorkUnit` from an `ImageCollection`, although it might be good to updates to all of the phases of reprojection including loading in a `WorkUnit` from disk/FITs files (which takes a couple of minutes).
2. In general for other lincc-frameworks projects we tend to use [tqdm](https://github.com/tqdm/tqdm) for tracking progress because it works pretty well out of the box. There are ways to configure it with `multiprocessing` futures as well for the parallel version of reproject.

**Comment by vlnistor** [comment]
Thank you for those clarifications - I'm looking at `discrete_piles_e2e.ipynb` to see an example of creating a `WorkUnit` from an `ImageCollection`. I installed the `lsst` package from [here](https://github.com/lsst/daf_butler) (`pip install git+https://github.com/lsst/daf_butler.git`). However, I am missing the test data specified in `REPO` path in the notebook. Is there some test data you can share ? Otherwise, I can try to use the `MockButler`

**Comment by maxwest-uw** [comment]
I think you shouldn't have to worry about installing the LSST stack to do development on this portion of KBMOD! If you just want to test against a basic `WorkUnit` we have one we use for testing included in the test directory ([this](https://github.com/dirac-institute/kbmod/blob/main/tests/data/shifted_wcs_diff_dimms_tiled.fits) one, it's also the one we run against for the reprojection unit tests). If we wanted to run tests against actual data we could try doing some runs with the data we have our HPC clusters, but I think the unit test one would be a good place to start !

**Comment by maxwest-uw** [comment]
^ this is just in relation to reprojection, thinking about it you might need the stack to work with `ImageCollection` generation, but I might need to defer to another dev about working with that

**Comment by vlnistor** [comment]
@maxwest-uw Made a [PR](https://github.com/dirac-institute/kbmod/pull/670) with a start on this. Some points to confirm but let's address them there

**Comment by maxwest-uw** [comment]
Need to add the TQDM loop to a few of the ImageCollection and WorkUnit functions so that we can track the progress of various large tasks in the reproject/KBMOD search pipeline.

Important requirement: needs to interact nicely with output files on HPCs like klone.

## Required Changes

tqdm should be added to the following places in the code:

- [ ]  https://github.com/dirac-institute/kbmod/blob/main/src/kbmod/image_collection.py#L531
- [x]  https://github.com/dirac-institute/kbmod/blob/main/src/kbmod/work_unit.py#L288
- [ ]  https://github.com/dirac-institute/kbmod/blob/main/src/kbmod/reprojection.py#L129
- [ ]  [Stretch Goal] https://github.com/dirac-institute/kbmod/blob/main/src/kbmod/reprojection.py#L271
    - [ ]  Working with parallel jobs and tqdm is kind of a PITA, so I’m marking this one as a stretch goal if you can find an easy way to do this.

## Testing

- [ ]  Test piping the output to a file and make sure that we can read the TQDM output nicely when not running directly from the command line.
